apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-gitops
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  automated:
    prune: true
    selfHeal: true
  source:
    path: manifests/ArgoCD101-GuestbookGitOps/
    repoURL: https://github.com/sonam11/ArgoCDRollouts
  
